import { CATEGORY_LABELS } from './categories';
import { circleAreaSquareKilometers, haversineDistance } from './geo';
import { isoDate } from './time';
import type { AnalysisResult,CategoryBreakdownItem,CrimeCategory,CrimeGroup,EvidenceBand,EvidenceConfidence,Incident } from '../types';
export interface AnalysisInput { incidents:Incident[]; center:readonly[number,number]; radiusMeters:number; windowDays:number; activeGroups:CrimeGroup[]; now:Date; truncated?:boolean; }
const isNightHour=(hour:number|null)=>hour!==null&&(hour>=22||hour<5);
function evidenceBand(relative:number|null,sample:number):EvidenceBand{if(relative===null||sample<5)return'insufficient';if(relative<.65)return'lower';if(relative<1.25)return'similar';if(relative<2)return'elevated';return'markedly-elevated';}
function evidenceConfidence(sample:number,truncated:boolean):EvidenceConfidence{if(truncated||sample<12)return'low';if(sample<40)return'medium';return'high';}
function categoryBreakdown(incidents:Incident[]):CategoryBreakdownItem[]{const counts=new Map<CrimeCategory,number>();for(const incident of incidents)counts.set(incident.category,(counts.get(incident.category)??0)+1);return Array.from(counts.entries()).map(([category,count])=>({category,count,share:incidents.length>0?count/incidents.length:0})).sort((a,b)=>b.count-a.count||CATEGORY_LABELS[a.category].localeCompare(CATEGORY_LABELS[b.category]));}
function dailyActivity(incidents:Incident[],nowEpochMs:number,windowDays:number){const days=Math.min(windowDays,30);const counts=new Map<string,number>();for(const incident of incidents){const date=isoDate(incident.occurredAtEpochMs);counts.set(date,(counts.get(date)??0)+1);}return Array.from({length:days},(_,index)=>{const offset=days-1-index;const date=isoDate(nowEpochMs-offset*86_400_000);return{date,count:counts.get(date)??0};});}
export function analyzeIncidents({incidents,center,radiusMeters,windowDays,activeGroups,now,truncated=false}:AnalysisInput):AnalysisResult{
 const nowMs=now.getTime();const currentStart=nowMs-windowDays*86_400_000;const previousStart=currentStart-windowDays*86_400_000;const active=new Set(activeGroups);const comparisonRadius=radiusMeters*3;
 const filtered=incidents.filter(i=>active.has(i.group)).filter(i=>Number.isFinite(i.occurredAtEpochMs)).map(incident=>({incident,distance:haversineDistance(center,incident.coordinates)})).filter(x=>x.distance<=comparisonRadius);
 const currentIncidents=filtered.filter(({incident,distance})=>distance<=radiusMeters&&incident.occurredAtEpochMs>=currentStart&&incident.occurredAtEpochMs<=nowMs).map(x=>x.incident).sort((a,b)=>b.occurredAtEpochMs-a.occurredAtEpochMs);
 const previousIncidents=filtered.filter(({incident,distance})=>distance<=radiusMeters&&incident.occurredAtEpochMs>=previousStart&&incident.occurredAtEpochMs<currentStart).map(x=>x.incident);
 const nearbyCurrentIncidents=filtered.filter(({incident,distance})=>distance>radiusMeters&&distance<=comparisonRadius&&incident.occurredAtEpochMs>=currentStart&&incident.occurredAtEpochMs<=nowMs).map(x=>x.incident);
 const mapIncidents=filtered.filter(({incident})=>incident.occurredAtEpochMs>=currentStart&&incident.occurredAtEpochMs<=nowMs).map(x=>x.incident);
 const innerArea=circleAreaSquareKilometers(radiusMeters);const nearbyArea=circleAreaSquareKilometers(comparisonRadius)-innerArea;const innerWeight=currentIncidents.reduce((s,i)=>s+i.severity,0);const nearbyWeight=nearbyCurrentIncidents.reduce((s,i)=>s+i.severity,0);const innerWeightedDensity=innerArea>0?innerWeight/innerArea:0;const nearbyWeightedDensity=nearbyArea>0?nearbyWeight/nearbyArea:0;const relativeActivity=nearbyWeightedDensity>0?innerWeightedDensity/nearbyWeightedDensity:null;
 const violentCount=currentIncidents.filter(i=>i.isViolent).length;const nightCount=currentIncidents.filter(i=>isNightHour(i.localHour)).length;const currentCount=currentIncidents.length;const previousCount=previousIncidents.length;const trendPercent=previousCount>0?((currentCount-previousCount)/previousCount)*100:null;const trendDirection=previousCount===0?(currentCount>0?'new':'none'):Math.abs(currentCount-previousCount)<1?'flat':currentCount>previousCount?'up':'down';const sample=currentCount+nearbyCurrentIncidents.length;
 return {currentIncidents,previousIncidents,nearbyCurrentIncidents,mapIncidents,currentCount,previousCount,violentCount,nightCount,violentShare:currentCount>0?violentCount/currentCount:0,nightShare:currentCount>0?nightCount/currentCount:0,trendPercent,trendDirection,innerWeightedDensity,nearbyWeightedDensity,relativeActivity,band:evidenceBand(relativeActivity,sample),confidence:evidenceConfidence(sample,truncated),categoryBreakdown:categoryBreakdown(currentIncidents),dailyActivity:dailyActivity(currentIncidents,nowMs,windowDays),latestObservedAt:currentIncidents[0]?.occurredAt??null};
}
export const BAND_COPY:Record<EvidenceBand,{label:string;detail:string}>={lower:{label:'Lower reported activity',detail:'Weighted incident density is lower than the surrounding comparison area.'},similar:{label:'Similar to nearby',detail:'Weighted incident density is broadly similar to the surrounding comparison area.'},elevated:{label:'Elevated reported activity',detail:'Weighted incident density is higher than the surrounding comparison area.'},'markedly-elevated':{label:'Markedly elevated activity',detail:'Weighted incident density is at least twice the surrounding comparison area.'},insufficient:{label:'Not enough evidence',detail:'The sample is too small for a stable comparison with the nearby area.'}};
