import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { analyzeIncidents } from '../domain/analysis';
import type { AnalysisResult,CrimeGroup,IncidentBatch,IncidentProvider,SelectedPlace } from '../types';
interface CachedBatch{batch:IncidentBatch;storedAt:number} const cache=new Map<string,CachedBatch>(); const CACHE_TTL=5*60_000; const TIMEOUT=20_000;
export interface IncidentAnalysisState{status:'idle'|'loading'|'ready'|'error';analysis:AnalysisResult|null;batch:IncidentBatch|null;error:string|null;refresh():void;}
interface Input{provider:IncidentProvider|null;place:SelectedPlace;radiusMeters:number;windowDays:number;activeGroups:CrimeGroup[];}
const keyFor=(p:IncidentProvider,place:SelectedPlace,r:number,d:number)=>[p.meta.id,place.coordinates[0].toFixed(4),place.coordinates[1].toFixed(4),r,d].join(':');
export function useIncidentAnalysis({provider,place,radiusMeters,windowDays,activeGroups}:Input):IncidentAnalysisState{const[status,setStatus]=useState<IncidentAnalysisState['status']>('idle');const[batch,setBatch]=useState<IncidentBatch|null>(null);const[error,setError]=useState<string|null>(null);const[version,setVersion]=useState(0);const requestId=useRef(0);const groupsKey=activeGroups.join(',');
 const refresh=useCallback(()=>{if(provider)cache.delete(keyFor(provider,place,radiusMeters,windowDays));setVersion(v=>v+1);},[provider,place,radiusMeters,windowDays]);
 useEffect(()=>{requestId.current+=1;const id=requestId.current;if(!provider){setStatus('idle');setBatch(null);setError(null);return;}const key=keyFor(provider,place,radiusMeters,windowDays);const cached=cache.get(key);if(cached&&Date.now()-cached.storedAt<CACHE_TTL){setBatch(cached.batch);setError(null);setStatus('ready');return;}const controller=new AbortController();let timedOut=false;const timeout=window.setTimeout(()=>{timedOut=true;controller.abort();},TIMEOUT);setStatus('loading');setError(null);void provider.fetchIncidents({center:place.coordinates,radiusMeters:radiusMeters*3,windowDays,now:new Date(),signal:controller.signal}).then(next=>{if(id!==requestId.current)return;cache.set(key,{batch:next,storedAt:Date.now()});setBatch(next);setStatus('ready');}).catch((reason:unknown)=>{if(id!==requestId.current)return;if(controller.signal.aborted&&!timedOut)return;setError(timedOut?'The official data portal did not respond within 20 seconds.':reason instanceof Error?reason.message:'The official data portal could not be reached.');setStatus('error');}).finally(()=>window.clearTimeout(timeout));return()=>{window.clearTimeout(timeout);controller.abort();};},[provider,place,radiusMeters,windowDays,version]);
 const analysis=useMemo(()=>batch?analyzeIncidents({incidents:batch.incidents,center:place.coordinates,radiusMeters,windowDays,activeGroups,now:new Date(),truncated:batch.truncated}):null,[batch,place.coordinates,radiusMeters,windowDays,groupsKey]);return{status,analysis,batch,error,refresh};}
